from faker import Faker
fake = Faker('ja_JP')
print("name" + " " + ":" + " " + fake.romanized_name())
print("country" + " " + ":" + " " + fake.country())
print("city" + " " + ":" + " " + fake.city())
print("zip code" + " " + ":" + " " + fake.zipcode())
print("street name" + " " + ":" + " " + fake.street_name())
print("license plate" + " " + ":" + " " + fake.license_plate())
print("phone number" + " " + ":" + " " + fake.phone_number())
print("email" + " " + ":" + " " + "given randomEmail")
print("username" + " " + ":" + " " + fake.user_name())
print("password" + " " + ":" + " " + fake.password(length=8, special_chars=True, digits=True, upper_case=True, lower_case=True))
print("iban" + " " + ":" + " " + fake.iban())
print("credit card" + " " + ":" + " " + fake.credit_card_number())
print("credit card security code" + " " + ":" + " " + fake.credit_card_security_code())
print("cryptocurrency code" + " " + ":" + " " + fake.cryptocurrency_code())
print("profession" + " " + ":" + " " + fake.job())
